package com.manurung.joko.sepatuadidas;

import java.util.ArrayList;

public class DataSepatu {
    public static String [][] data = new String[][]{
            {"Nemeziz 19.1 Firm Ground Boots", "Rp. 3.000.000","Nemeziz isn't just a boot. It's a commitment that skills should be about wins, not likes. If you'd take celebrity over silverware, get out of here. But if you're ready to rip up the pitch to carry your team to victory, read on. The stretchy upper on these football boots is weaved using different widths and tensions of tape to match your foot shape. The result is a lockdown fit that provides stability and a direct touch. A split outsole flexes with every twist and turn. Adaptive fit Sports taping-inspired Tension Tape reduces restrictions on the in-step for a truly personalised fit Quick entry Stretchy tape at the collar separates easily for speedy entry Made for radical moves A split outsole and Torsion System insole board provide the flexibility for every twist and turn; Explosive acceleration and high-speed turns supported by an agility stud configuration" ,"https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/F/3/F34407_SL_eCom.jpg"},
            {"Grand Court Shoes", "Rp. 1.100.000", "A modern update to '70s style. These court-inspired shoes have a smooth leather upper that rides on a translucent outsole. A cushioned sockliner provides comfort for when you're tackling your to-do list.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/E/E/EE7883_SL_eCom.jpg"},
            {"DURAMO 9 SHOES", "Rp. 800.000", "These men's versatile running shoes are ideal for the treadmill or the trail. They feature a durable two-layer mesh upper for breathability and a seamless print overlay for additional support. Pillow-soft Cloudfoam cushions every stride, while the durable outsole provides long-lasting wear. Shoe type Neutral shoes offer flexibility and versatility, with premium cushioning Cushioned comfort Cloudfoam midsole for step-in comfort and superior cushioning Targeted support Haptic print overlay on upper provides seamless support where you need it Outstanding durability Adiwear outsole offers the ultimate in high-wear durability", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/E/E/EE7923_SL_eCom.jpg"},
            {"Stan Smith Shoes", "Rp. 1.500.000", "The instantly recognisable classic gets a cheeky bit of signature flourish. These Stan Smith shoes update the iconic look with cursive heel branding that reads \"Stan\" on one side and \"Smith\" on the other. The soft leather upper includes the famous perforated 3-Stripes.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/E/E/EE5818_SL_eCom.jpg"},
            {"ULTRABOOST PARIS SHOES", "Rp. 2.800.000", "From the cobbled hills of Montmartre to the bridges over the Seine, Paris rewards runners with its beauty and charm. These running shoes celebrate the City of Lights. They have a knit upper with a second-skin fit. Responsive cushioning returns energy to your stride.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/F/V/FV2586_SL_eCom.jpg"},
            {"SEPATU BOLA PREDATOR 19.4 S FLEXIBLE GROUND", "Rp. 800.000", "Predator bukan sekadar sepatu bola. Melainkan pernyataan bahwa aksi menjadi bukti nyata, bukan kata-kata. Jika kontrol Anda tidak sebaik apa yang Anda katakan, lebih baik diam. Namun jika Anda siap untuk mendominasi hingga akhir pertandingan, teruskan tekad Anda. Upper berbahan sintetis yang lembut pada sepatu bola ini dilengkapi dengan bagian tumit yang didesain khusus untuk menghasilkan comfortable fit. Tekstur timbul di bagian forefoot menghasilkan daya cengkeram terhadap bola untuk meningkatkan kontrol saat melakukan umpan dan tendangan.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/E/F/EF0384_SL_eCom.jpg"},
            {"Sensebounce+ Street Shoes", "Rp. 1.000.000", "These dynamic running shoes for men offer outstanding traction, cushioning and fit that's tailored to the streets. It's built using 3D moulding that follows the shape of the foot for a supportive, locked-in feel. A wide forefoot delivers increased surface contact for added stability, and a grippy rubber outsole is ideal for dodging urban obstacles.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/G/2/G27274_SL_eCom.jpg"},
            {"Sepatu Pureboost Go", "Rp. 1.800.000", "Didesain untuk melewati trotoar, sudut jalan, dan tepi jalan yang tidak rata, sepatu running bertipe natural ini dilengkapi landing zone yang lebih lebar dan heel plate agar lebih stabil. Upper rajut yang ringan dan elastis menopang langkah kaki natural Anda. Bantalan dengan keunggulan efisiensi energi dan outsole fleksibel menghasilkan aktivitas lari yang mulus dan nyaman. Energi berkelanjutan Boost adalah bantalan kami yang paling responsif, menghasilkan energy return terbaik: Semakin besar energi yang dilepas, maka semakin besar yang diperoleh Natural fit Moulded heel counter dengan teknologi Fitcounter yang menghasilkan natural fit untuk mengoptimalkan gerakan otot Achilles", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/D/9/D97420_SL_eCom.jpg"},
            {"Sepatu Alphabounce Beyond", "Rp. 1.700.000", "Saat napas Anda terasa ringan, artinya Anda berada dalam tempo lari yang tepat. Sepatu running ini didesain secara khusus untuk cross training, dengan upper Forgedmesh tanpa jahitan yang mengikuti bentuk kaki Anda dengan nyaman dan memberikan topangan kuat untuk gerakan side-to-side. Sepatu running ini memadukan outsole berdaya cengkeram terbaik dengan pantulan Bounce yang memberi tenaga dalam setiap langkah untuk kenyamanan dalam waktu yang lama.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/A/C/AC8274_SL_eCom.jpg"},
            {"D.O.N. Issue #1 Shoes", "Rp. 1.600.000", "These basketball shoes reflect Donovan Mitchell's determination to succeed. The herringbone-pattern rubber outsole provides the traction needed to make quick and decisive cuts in the paint. A propulsion clip on the side gives you lateral support for dynamic moves, while a flexible Bounce midsole offers instant step-in comfort and a cushioned, responsive ride. Outsole details represent the stops on Mitchell's journey from Brewster Academy in New Hampshire to basketball superstardom.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/E/F/EF2401_SL_eCom.jpg"},
            {"Marquee Boost Shoes", "Rp. 2.200.000", "A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/E/H/EH2451_SL_eCom.jpg"},
            {"Sepatu Pro Spark 2018", "Rp. 1.000.000", "Bermain maksimal dan mencetak skor sepanjang permainan. Sepatu basket ini memiliki kerah berlapis busa untuk meningkatkan topangan di bagian pergelangan kaki ketika melakukan perubahan arah dengan cepat. Midsole dari bahan busa membantu Anda meredam efek lompatan dengan nyaman, dan outsole dari bahan karet menghasilkan traksi ketika Anda berputar dan berkelok untuk mencetak skor.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/G/2/G25777_SL_eCom.jpg"},
            {"Sepatu Cloudfoam Racer TR", "Rp. 770.000", "Terinspirasi sepatu trail running, siap digunakan di jalanan. Sepatu untuk wanita ini dibuat untuk petualangan urban, dengan konstruksi mesh dan tampilan bertekstur. Bantalan cloudfoam menambahkan kenyamanan.", "https://static.shop.adidas.co.id/media/catalog/product/cache/2/thumbnail/1200x/9df78eab33525d08d6e5fb8d27136e95/C/G/CG5764_SL_eCom.jpg"},
    };

    public static ArrayList<Sepatu> getListData(){
        Sepatu sepatu = null;
        ArrayList<Sepatu> list = new ArrayList<>();

        for (int i = 0 ; i< data.length;i++){
            sepatu = new Sepatu();
            sepatu.setNamaSepatu(data[i][0]);
            sepatu.setHargaSepatu(data[i][1]);
            sepatu.setDescSepatu(data[i][2]);
            sepatu.setPhoto(data[i][3]);

            list.add(sepatu);
        }
        return list;
    }
}
